indexing-settings:
  sites:
    #    - url: https://www.lenta.ru
    #      name: Lenta.ru
              - url: https://www.skillbox.ru
                name: Skillbox
    #            - url: https://www.playback.ru
    #              name: PlayBack.Ru
    #    - url: https://volochek.life/
    #      name: volochek.life
    #    - url: http://radiomv.ru/
    #      name: radiomv.ru
    #    - url: https://ipfran.ru/
    #      name: ipfran.ru
    #    - url: https://dimonvideo.ru/
    #      name: dimonvideo.ru
    #    - url: https://nikoartgallery.com/
    #      name: nikoartgallery.com
    #        - url: https://et-cetera.ru/mobile/
    #          name: et-cetera.ru
    #        - url: https://www.lutherancathedral.ru/
    #          name: lutherancathedral.ru
    #    - url: https://dombulgakova.ru/
    #      name: dombulgakova.ru
    #        - url: https://www.svetlovka.ru/
    #          name: www.svetlovka.ru

#    - url: https://sendel.ru/
#      name: sendel.ru

server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Testtest
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create #update   create-drop  create validate
    show-sql: true
